name: MidnightCore-Commons-Bukkit
main: net.absolutioncraft.commons.bukkit.CommonsBukkit
version: ${project.version}-${git.commit.id.abbrev}
depend: [MidnightCore-API-Bukkit]
author: MelonDev, GatitoUwU